# Generated by Django 5.2.7 on 2025-10-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tamano_lote', models.FloatField()),
                ('precio_lote', models.FloatField()),
                ('minimo_lotes', models.FloatField()),
                ('unidades_restantes', models.FloatField()),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('abreviado', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('S', 'Simple'), ('G', 'Gran Formato')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoGranFormato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_m2', models.FloatField()),
                ('precio_m2', models.FloatField()),
                ('producto', models.OneToOneField(limit_choices_to={'categoria': 'G'}, on_delete=django.db.models.deletion.CASCADE, related_name='gran_formato', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto Gran Formato',
                'verbose_name_plural': 'Productos Gran Formato',
            },
        ),
        migrations.CreateModel(
            name='ProductoIntervalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.FloatField()),
                ('precio_con_iva', models.FloatField()),
                ('duplex', models.BooleanField()),
                ('producto', models.ForeignKey(limit_choices_to={'categoria': 'S'}, on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto Intervalo',
                'verbose_name_plural': 'Productos Intervalos',
                'unique_together': {('producto', 'desde', 'duplex')},
            },
        ),
        migrations.CreateModel(
            name='ProductoUtilizaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utiliza_inventario', models.FloatField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto utiliza Inventario',
                'verbose_name_plural': 'Productos utilizan Inventario',
                'unique_together': {('producto', 'inventario')},
            },
        ),
    ]
