# Generated by Django 5.2.7 on 2025-10-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productointervalo',
            name='desde',
            field=models.PositiveIntegerField(),
        ),
    ]
