# Generated by Django 5.2.7 on 2025-10-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_productointervalo_desde'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
