# Generated by Django 5.2.7 on 2025-10-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='precio_lote',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productogranformato',
            name='precio_m2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productointervalo',
            name='precio_con_iva',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
