# Generated by Django 5.2.7 on 2025-11-12 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuraciones del sistema',
            },
        ),
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'tipo_alerta',
                    models.CharField(
                        choices=[
                            ('low_stock', 'Bajo stock'),
                            ('old_product', 'Producto antiguo'),
                            ('unusual_movement', 'Movimiento inusual'),
                            ('high_rotation', 'Alta rotación'),
                        ],
                        max_length=30,
                    ),
                ),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                (
                    'producto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alertas',
                        to='productos.producto',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Alerta de inventario',
                'verbose_name_plural': 'Alertas de inventario',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'accion',
                    models.CharField(
                        choices=[
                            ('create', 'Creación'),
                            ('update', 'Modificación'),
                            ('delete', 'Eliminación'),
                            ('approve', 'Aprobación'),
                            ('login', 'Inicio de sesión'),
                            ('export', 'Exportación de datos'),
                        ],
                        max_length=20,
                    ),
                ),
                ('descripcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                (
                    'usuario',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-creado'],
            },
        ),
    ]
