# Generated by Django 5.2.7 on 2026-05-30 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
