# Generated by Django 5.2.7 on 2026-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_registroactividad_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactividad',
            name='segmentos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
