# Generated by Django 5.2.7 on 2026-06-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0007_alter_equipocliente_alias'),
        ('system', '0003_registroactividad_segmentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertainventario',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='organizacion.sucursal'),
        ),
    ]
