# Generated by Django 5.2.7 on 2026-06-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0007_alter_equipocliente_alias'),
        ('system', '0005_fill_and_fix_alerta_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactividad',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='organizacion.sucursal'),
        ),
    ]
