# Generated by Django 5.2.7 on 2026-06-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_registroactividad_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='accion',
            field=models.CharField(
                choices=[
                    ('create', 'Creación'),
                    ('update', 'Modificación'),
                    ('delete', 'Eliminación'),
                    ('approve', 'Aprobación'),
                    ('login', 'Inicio de sesión'),
                    ('export', 'Exportación de datos'),
                    ('query', 'Consulta chatbot'),
                ],
                max_length=20,
            ),
        ),
    ]
