# Generated by Django 5.2.7 on 2025-10-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
