# Generated by Django 5.2.7 on 2025-10-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
