# Generated by Django 5.2.7 on 2025-11-12 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Categoría',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                (
                    'contact_name',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'internal_code',
                    models.CharField(
                        max_length=50, unique=True, verbose_name='Código interno'
                    ),
                ),
                (
                    'description',
                    models.CharField(max_length=255, verbose_name='Descripción'),
                ),
                (
                    'model_name',
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name='Modelo'
                    ),
                ),
                (
                    'serial_or_lot',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Número de serie/lote',
                    ),
                ),
                (
                    'quantity_available',
                    models.PositiveIntegerField(
                        default=0, verbose_name='Cantidad disponible'
                    ),
                ),
                (
                    'min_stock',
                    models.PositiveIntegerField(default=0, verbose_name='Stock mínimo'),
                ),
                (
                    'unit',
                    models.CharField(
                        default='pieza', max_length=50, verbose_name='Unidad de medida'
                    ),
                ),
                (
                    'purchase_price',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    'sale_price',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Activo'),
                            ('inactive', 'Inactivo'),
                            ('discontinued', 'Descontinuado'),
                        ],
                        default='active',
                        max_length=20,
                    ),
                ),
                ('notes', models.TextField(blank=True, null=True)),
                (
                    'brand',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='productos',
                        to='productos.marca',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='productos',
                        to='productos.categoría',
                    ),
                ),
                (
                    'supplier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='productos',
                        to='productos.proveedor',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['brand__name', 'description'],
            },
        ),
    ]
