# Generated by Django 5.2.7 on 2025-11-12 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Categoría',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=150)),
                (
                    'nombre_contacto',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'codigo_interno',
                    models.CharField(
                        max_length=50, unique=True, verbose_name='Código interno'
                    ),
                ),
                (
                    'descripcion',
                    models.CharField(max_length=255, verbose_name='Descripción'),
                ),
                (
                    'nombre_modelo',
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name='Modelo'
                    ),
                ),
                (
                    'serie_lote',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Número de serie/lote',
                    ),
                ),
                (
                    'cantidad_disponible',
                    models.PositiveIntegerField(
                        default=0, verbose_name='Cantidad disponible'
                    ),
                ),
                (
                    'min_stock',
                    models.PositiveIntegerField(default=0, verbose_name='Stock mínimo'),
                ),
                (
                    'unidad',
                    models.CharField(
                        default='pieza', max_length=50, verbose_name='Unidad de medida'
                    ),
                ),
                (
                    'precio_compra',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    'precio_venta',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('activo', 'Activo'),
                            ('inactivo', 'Inactivo'),
                            ('descontinuado', 'Descontinuado'),
                        ],
                        default='active',
                        max_length=20,
                    ),
                ),
                ('notas', models.TextField(blank=True, null=True)),
                (
                    'categoria',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='productos',
                        to='productos.categoría',
                    ),
                ),
                (
                    'marca',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='productos',
                        to='productos.marca',
                    ),
                ),
                (
                    'proveedor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='productos',
                        to='productos.proveedor',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['marca__nombre', 'descripcion'],
            },
        ),
    ]
