# Generated by Django 5.2.7 on 2025-11-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={
                'ordering': ['equipo__marca__nombre', 'equipo__nombre', 'descripcion'],
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.RemoveField(model_name='producto', name='marca',),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                (
                    'marca',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='equipos',
                        to='productos.marca',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='equipo',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='productos',
                to='productos.equipo',
            ),
        ),
    ]
