# Generated by Django 5.2.7 on 2025-11-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'productos',
            '0002_alter_producto_options_remove_producto_marca_equipo_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(model_name='producto', name='nombre_modelo',),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='productos',
                to='productos.categoría',
            ),
        ),
        migrations.AlterField(
            model_name='producto',
            name='equipo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='productos',
                to='productos.equipo',
            ),
        ),
        migrations.AlterField(
            model_name='producto',
            name='serie_lote',
            field=models.CharField(max_length=100, verbose_name='Número de serie/lote'),
        ),
    ]
