# Generated by Django 5.2.7 on 2025-12-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_nombre_modelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='producto', name='precio_compra',),
        migrations.RemoveField(model_name='producto', name='precio_venta',),
    ]
