# Generated by Django 5.2.7 on 2025-12-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_precio_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='producto', name='unidad',),
    ]
