# Generated by Django 5.2.7 on 2025-12-01 16:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_unidad'),
    ]

    operations = [
        migrations.AlterModelOptions(name='producto', options={},),
        migrations.RemoveField(model_name='producto', name='cantidad_disponible',),
        migrations.RemoveField(model_name='producto', name='min_stock',),
        migrations.RemoveField(model_name='producto', name='notas',),
        migrations.RemoveField(model_name='producto', name='proveedor',),
        migrations.RemoveField(model_name='producto', name='serie_lote',),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(default='pieza', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='productos.categoría'
            ),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_interno',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='equipo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='productos.equipo'
            ),
        ),
        migrations.AlterField(
            model_name='producto',
            name='status',
            field=models.CharField(
                choices=[
                    ('activo', 'Activo'),
                    ('inactivo', 'Inactivo'),
                    ('descontinuado', 'Descontinuado'),
                ],
                default='activo',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('codigo_lote', models.CharField(max_length=100, unique=True)),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_restante', models.PositiveIntegerField()),
                (
                    'fecha_entrada',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                (
                    'producto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lotes',
                        to='productos.producto',
                    ),
                ),
                (
                    'proveedor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='productos.proveedor',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'codigo_unidad',
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                ('status', models.CharField(default='disponible', max_length=20)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                (
                    'lote',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='unidades',
                        to='productos.lote',
                    ),
                ),
            ],
        ),
    ]
