# Generated by Django 5.2.7 on 2025-12-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
    ]
