# Generated by Django 5.2.7 on 2025-12-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_lote_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='min_stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
