# Generated by Django 5.2.7 on 2025-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='example', max_length=255),
            preserve_default=False,
        ),
    ]
