# Generated by Django 5.2.7 on 2025-12-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_sku'),
    ]

    operations = [
        migrations.RemoveField(model_name='lote', name='proveedor',),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='productos.proveedor',
            ),
        ),
    ]
