# Generated by Django 5.2.7 on 2025-12-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_lote_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
