# Generated by Django 5.2.7 on 2025-12-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_producto_sku'),
    ]

    operations = [
        migrations.RemoveField(model_name='producto', name='equipo',),
        migrations.AddField(
            model_name='producto',
            name='equipos',
            field=models.ManyToManyField(blank=True, to='productos.equipo'),
        ),
    ]
