# Generated by Django 5.2.7 on 2025-12-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_producto_equipo_producto_equipos'),
    ]

    operations = [
        migrations.RemoveField(model_name='equipo', name='descripcion',),
        migrations.RemoveField(model_name='marca', name='descripcion',),
        migrations.AddField(
            model_name='equipo', name='activo', field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marca', name='activo', field=models.BooleanField(default=True),
        ),
    ]
