# Generated by Django 5.2.7 on 2026-01-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_cliente'),
        (
            'productos',
            '0013_remove_equipo_descripcion_remove_marca_descripcion_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoCliente',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('contador_uso', models.PositiveIntegerField()),
                (
                    'cliente',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='equipos',
                        to='organizacion.cliente',
                    ),
                ),
                (
                    'equipo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clientes',
                        to='productos.equipo',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Equipo de cliente',
                'verbose_name_plural': 'Equipos de clientes',
                'unique_together': {('equipo', 'cliente')},
            },
        ),
    ]
