# Generated by Django 5.2.7 on 2026-01-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_equipocliente'),
    ]

    operations = [
        migrations.DeleteModel(name='EquipoCliente',),
    ]
