# Generated by Django 5.2.7 on 2026-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_delete_equipocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='equipos',
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={'activo': True, 'marca__activo': True},
                to='productos.equipo',
            ),
        ),
    ]
