# Generated by Django 5.2.7 on 2026-04-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_alter_producto_equipos'),
    ]

    operations = [
        migrations.RemoveField(model_name='lote', name='cantidad_restante',),
    ]
