# Generated by Django 5.2.7 on 2026-04-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_remove_lote_cantidad_restante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='status',
            field=models.CharField(
                choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')],
                default='activo',
                max_length=20,
            ),
        ),
    ]
