# Generated by Django 5.2.7 on 2026-05-21 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_alter_producto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vida_util',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
