# Generated by Django 5.2.7 on 2025-11-12 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'tipo_entrada',
                    models.CharField(
                        choices=[
                            ('compra', 'Compra / Proveedor'),
                            ('devolucion', 'Devolución'),
                            ('ajuste', 'Ajuste de inventario'),
                        ],
                        default='compra',
                        max_length=20,
                    ),
                ),
                (
                    'numero_factura',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Factura / Orden de compra',
                    ),
                ),
                (
                    'cantidad',
                    models.PositiveIntegerField(verbose_name='Cantidad ingresada'),
                ),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'producto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entradas',
                        to='productos.producto',
                    ),
                ),
                (
                    'proveedor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='productos.proveedor',
                    ),
                ),
                (
                    'recibido_por',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='entradas_recibidas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Entrada de inventario',
                'verbose_name_plural': 'Entradas de inventario',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PasoAprobacion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('object_id', models.BigIntegerField()),
                ('paso', models.PositiveIntegerField(default=1)),
                ('aprobado', models.BooleanField(default=False)),
                ('aprobado_fecha', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'user_aprueba',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='pasos_aprobacion',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paso de aprobación',
                'verbose_name_plural': 'Flujo de aprobaciones',
                'ordering': ['content_type', 'object_id', 'paso'],
            },
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'tipo_salida',
                    models.CharField(
                        choices=[
                            ('project', 'Proyecto / Cliente'),
                            ('rental', 'Equipo en renta'),
                            ('internal', 'Uso interno'),
                            ('adjustment', 'Ajuste de inventario'),
                        ],
                        default='project',
                        max_length=20,
                    ),
                ),
                (
                    'nombre_cliente',
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    'tecnico',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Técnico responsable',
                    ),
                ),
                (
                    'equipo_asociado',
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name='Equipo asociado',
                    ),
                ),
                (
                    'cantidad',
                    models.PositiveIntegerField(verbose_name='Cantidad entregada'),
                ),
                (
                    'recibido_por',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Recibido por',
                    ),
                ),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'entregado_por',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='salidas_entregadas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'producto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='salidas',
                        to='productos.producto',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Salida de inventario',
                'verbose_name_plural': 'Salidas de inventario',
                'ordering': ['-creado'],
            },
        ),
    ]
