# Generated by Django 5.2.7 on 2025-11-12 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('object_id', models.BigIntegerField()),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                (
                    'approver',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='pasos_aprobacion',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paso de aprobación',
                'verbose_name_plural': 'Flujo de aprobaciones',
                'ordering': ['content_type', 'object_id', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'entry_type',
                    models.CharField(
                        choices=[
                            ('purchase', 'Compra / Proveedor'),
                            ('return', 'Devolución'),
                            ('adjustment', 'Ajuste de inventario'),
                        ],
                        default='purchase',
                        max_length=20,
                    ),
                ),
                (
                    'invoice_number',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Factura / Orden de compra',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(verbose_name='Cantidad ingresada'),
                ),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entradas',
                        to='productos.producto',
                    ),
                ),
                (
                    'received_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='entradas_recibidas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'supplier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='productos.proveedor',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Entrada de inventario',
                'verbose_name_plural': 'Entradas de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryExit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'exit_type',
                    models.CharField(
                        choices=[
                            ('project', 'Proyecto / Cliente'),
                            ('rental', 'Equipo en renta'),
                            ('internal', 'Uso interno'),
                            ('adjustment', 'Ajuste de inventario'),
                        ],
                        default='project',
                        max_length=20,
                    ),
                ),
                (
                    'client_name',
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    'technician',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Técnico responsable',
                    ),
                ),
                (
                    'related_equipment',
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name='Equipo asociado',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(verbose_name='Cantidad entregada'),
                ),
                (
                    'received_by',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Recibido por',
                    ),
                ),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'delivered_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='salidas_entregadas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='salidas',
                        to='productos.producto',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Salida de inventario',
                'verbose_name_plural': 'Salidas de inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
