# Generated by Django 5.2.7 on 2025-11-12 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasoaprobacion',
            options={
                'ordering': ['paso'],
                'verbose_name': 'Paso de aprobación',
                'verbose_name_plural': 'Flujo de aprobaciones',
            },
        ),
        migrations.RemoveField(model_name='pasoaprobacion', name='content_type',),
        migrations.RemoveField(model_name='pasoaprobacion', name='object_id',),
        migrations.AddField(
            model_name='pasoaprobacion',
            name='entrada',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pasos_aprobacion',
                to='movimiento.entradainventario',
            ),
        ),
        migrations.AddField(
            model_name='pasoaprobacion',
            name='salida',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pasos_aprobacion',
                to='movimiento.salidainventario',
            ),
        ),
    ]
