# Generated by Django 5.2.7 on 2025-11-24 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0003_entradainventario_aprobado_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name='entradainventario', name='proveedor',),
        migrations.RemoveField(model_name='salidainventario', name='equipo_asociado',),
        migrations.AlterField(
            model_name='entradainventario',
            name='numero_factura',
            field=models.CharField(
                max_length=100, verbose_name='Factura / Orden de compra'
            ),
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='recibido_por',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='entradas_recibidas',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='entregado_por',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='salidas_entregadas',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='nombre_cliente',
            field=models.CharField(max_length=150),
        ),
    ]
