# Generated by Django 5.2.7 on 2025-12-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0004_remove_entradainventario_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidainventario',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='tecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
