# Generated by Django 5.2.7 on 2025-12-01 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0005_alter_salidainventario_recibido_por_and_more'),
        ('productos', '0010_remove_lote_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(model_name='entradainventario', name='cantidad',),
        migrations.RemoveField(model_name='entradainventario', name='producto',),
        migrations.RemoveField(model_name='salidainventario', name='cantidad',),
        migrations.RemoveField(model_name='salidainventario', name='producto',),
        migrations.AlterField(
            model_name='entradainventario',
            name='numero_factura',
            field=models.CharField(max_length=100, verbose_name='Factura / Orden'),
        ),
        migrations.CreateModel(
            name='EntradaItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('cantidad', models.PositiveIntegerField()),
                (
                    'entrada',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='movimiento.entradainventario',
                    ),
                ),
                (
                    'producto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='productos.producto',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Item de entrada',
                'verbose_name_plural': 'Items de entrada',
            },
        ),
        migrations.CreateModel(
            name='SalidaItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('cantidad', models.PositiveIntegerField()),
                (
                    'producto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='productos.producto',
                    ),
                ),
                (
                    'salida',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='movimiento.salidainventario',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Item de salida',
                'verbose_name_plural': 'Items de salida',
            },
        ),
    ]
