# Generated by Django 5.2.7 on 2025-12-05 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0006_remove_entradainventario_cantidad_and_more'),
        ('productos', '0011_alter_producto_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name='entradaitem', name='entrada',),
        migrations.RemoveField(model_name='entradaitem', name='producto',),
        migrations.RemoveField(model_name='salidainventario', name='entregado_por',),
        migrations.RemoveField(model_name='salidainventario', name='user_aprueba',),
        migrations.RemoveField(model_name='salidaitem', name='salida',),
        migrations.RemoveField(model_name='salidaitem', name='producto',),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'tipo',
                    models.CharField(
                        choices=[
                            ('entrada', 'Entrada de inventario'),
                            ('salida', 'Salida de inventario'),
                        ],
                        max_length=10,
                    ),
                ),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobado', models.BooleanField(default=False)),
                ('aprobado_fecha', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                (
                    'creado_por',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='movimientos_creados',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user_aprueba',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='movimientos_aprobados',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('tecnico', models.CharField(blank=True, max_length=120, null=True)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                (
                    'movimiento',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='detalle_salida',
                        to='movimiento.movimiento',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Detalles de salida',
                'verbose_name_plural': 'Detalles de salidas',
                'ordering': ['-movimiento__creado'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('numero_factura', models.CharField(max_length=100)),
                (
                    'recibido_por',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'movimiento',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='detalle_entrada',
                        to='movimiento.movimiento',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Detalles de entrada',
                'verbose_name_plural': 'Detalles de entradas',
                'ordering': ['-movimiento__creado'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('cantidad', models.PositiveIntegerField()),
                (
                    'movimiento',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='movimiento.movimiento',
                    ),
                ),
                (
                    'producto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='productos.producto',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Item de movimiento',
                'verbose_name_plural': 'Items de movimientos',
                'ordering': ['-movimiento__creado', 'producto__codigo_interno'],
            },
        ),
        migrations.DeleteModel(name='EntradaInventario',),
        migrations.DeleteModel(name='EntradaItem',),
        migrations.DeleteModel(name='SalidaInventario',),
        migrations.DeleteModel(name='SalidaItem',),
    ]
