# Generated by Django 5.2.7 on 2025-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0007_remove_entradaitem_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesalida',
            name='requiere_aprobacion',
            field=models.BooleanField(default=True),
        ),
    ]
