# Generated by Django 5.2.7 on 2025-12-05 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0008_alter_detallesalida_requiere_aprobacion'),
        ('organizacion', '0003_cliente'),
    ]

    operations = [
        migrations.RemoveField(model_name='detallesalida', name='nombre_cliente',),
        migrations.AddField(
            model_name='detallesalida',
            name='cliente',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='salidas_inventario',
                to='organizacion.cliente',
            ),
            preserve_default=False,
        ),
    ]
