# Generated by Django 5.2.7 on 2026-04-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0009_remove_detallesalida_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='detallesalida', name='requiere_aprobacion',),
    ]
