# Generated by Django 5.2.7 on 2026-04-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0010_remove_detallesalida_requiere_aprobacion'),
        ('productos', '0017_remove_lote_cantidad_restante'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoitem',
            name='lote',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='productos.lote',
            ),
        ),
    ]
