# Generated by Django 5.2.7 on 2026-05-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0011_movimientoitem_lote'),
        ('organizacion', '0006_cliente_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoitem',
            name='contador_uso_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoitem',
            name='equipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.equipocliente'),
        ),
    ]
