# Generated by Django 5.2.7 on 2026-06-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0012_movimientoitem_contador_uso_snapshot_and_more'),
        ('organizacion', '0007_alter_equipocliente_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='organizacion.sucursal'),
        ),
    ]
