# Generated by Django 5.2.7 on 2026-06-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0014_fill_and_fix_movimiento_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoitem',
            name='cambio_anticipado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientoitem',
            name='motivo_cambio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
