# Generated by Django 5.2.7 on 2025-11-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='Almacen',),
    ]
