# Generated by Django 5.2.7 on 2025-12-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_delete_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=200)),
                (
                    'tipo',
                    models.CharField(
                        choices=[
                            ('fisica', 'Persona Física'),
                            ('moral', 'Persona Moral'),
                        ],
                        default='fisica',
                        max_length=10,
                    ),
                ),
                (
                    'rfc',
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['nombre'],},
        ),
    ]
