# Generated by Django 5.2.7 on 2026-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_equipocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipocliente',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
