# Generated by Django 5.2.7 on 2026-04-16 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0005_equipocliente_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sucursal',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='clientes',
                to='organizacion.sucursal',
            ),
            preserve_default=False,
        ),
    ]
