# Generated by Django 5.2.7 on 2026-05-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0006_cliente_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocliente',
            name='alias',
            field=models.CharField(default='alias', max_length=100),
            preserve_default=False,
        ),
    ]
